services:
  nginx:
    image: custom-nginx:1
    build: ./requirements/nginx/
    ports:
      - '443'
    depends_on:
      - wordpress

  wordpress:
      image: custom-wordpress:1
      build: ./requirements/wordpress/
      ports:
        - '9000'
      volumes:
        - wordpress:/

      environment:
        WORDPRESS_DB_HOST: db
        WORDPRESS_DB_USER: wordpress
        WORDPRESS_DB_PASSWORD: wordpress
        WORDPRESS_DB_NAME: wordpress
        WORDPRESS_TABLE_PREFIX: wp_
        WORDPRESS_CONFIG_EXTRA: |
          define('WPLANG', 'fr_FR'); # Définit la langue par défaut
      depends_on:
        mariadb

  mariadb:
      image: custom-mariadb:1
      build: ./requirements/mariadb/
      ports:
        -'3306'

  volumes:
  -
